### ISSUE TITLE
chore: メニューのアイコンの位置を統一する

### ISSUE THREAD

**Issue by yupix** [TeamBlackCrystal/ayuskey-legacy#68]
## Summary

なんか
- デッキ
- ダークテーマ系
だけ違うの気になる

今これ
![image](https://user-images.githubusercontent.com/50538210/183093144-6b9c291c-48bb-4a60-b62c-696fd2c19a4a.png)

やるとしたらした
![image](https://user-images.githubusercontent.com/50538210/183093340-52df7774-6ea9-491e-a03b-77f408884eec.png)

**Comment by yupix** [comment]
@sousuke0422 意見欲しいです

**Comment by sousuke0422** [comment]
LGTM!
